spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: 123456
  shardingsphere:
    datasource:
      names: test0,test1
      test0:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3306/test0
        username: root
        password: 123456
      test1:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3306/test1
        username: root
        password: 123456
    sharding:
      default-database-strategy:
        inline:
          sharding-column: age
          algorithm-expression: test$->{age % 2}
      tables:
        user:
          actual-data-nodes: test$->{0..1}.user$->{0..2}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: user$->{id%3}
    props:
      sql:
        show:
          true


